### ISSUE TITLE
Prevent word wrapping

### ISSUE THREAD

**Issue by RichardB01** [SirWumpus/ioccc-ae#1]
When the text is longer than the width of the screen are wraps the text. Is there a way to stop wrapping and move the display horizontally?

**Comment by SirWumpus** [comment]
No.  The original design was based on historical `vi(1)` behaviour, which does not support horizontal scrolling.  To do so would require a major overhaul (rewrite) of the display function, plus option to turn on/off the behaviour and extra key bindings.   This behaviour has stood since 1991 and the 1993 revisions.   I'm not inclined to change the functionality at this point in time.
